//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LesGrandesCoudraies.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Role = new HashSet<Role>();
            this.Vote = new HashSet<Vote>();
            this.Message = new HashSet<Message>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Role> Role { get; set; }
        public virtual ICollection<Vote> Vote { get; set; }
        public virtual ICollection<Message> Message { get; set; }
    }
}
