//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LesGrandesCoudraies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.AuthorizedRoles = new HashSet<Role>();
            this.Comment = new HashSet<Comment>();
            this.Vote = new HashSet<Vote>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int UserId { get; set; }
        public string Summary { get; set; }
        public byte[] Content { get; set; }
        public System.DateTime DateArticle { get; set; }
        public System.DateTime DateTarget { get; set; }
        public bool AllowVote { get; set; }
        public bool AllowComment { get; set; }
        public int MenuId { get; set; }
    
        public virtual User Owner { get; set; }
        public virtual ICollection<Role> AuthorizedRoles { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ICollection<Vote> Vote { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
