//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LesGrandesCoudraies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Role = new HashSet<Role>();
            this.ArticleSet = new HashSet<Article>();
            this.Comment = new HashSet<Comment>();
            this.Vote = new HashSet<Vote>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Building { get; set; }
        public string Apartment { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Role> Role { get; set; }
        public virtual ICollection<Article> ArticleSet { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ICollection<Vote> Vote { get; set; }
    }
}
